### ISSUE TITLE
Send and receive params on the AAD callback

### ISSUE THREAD

**Issue by kaiomagalhaes** [AzureAD/azure-activedirectory-library-for-ruby#41]
Does someone know if it is possible and if it is how or where I can find how to do it?
The idea is to add some params on the AAD auth and receive them along side with the keys.

**Comment by Ricalo** [comment]
Mmm... I haven't tried with this library, but you could try to send your data in the **state** parameter. You'll get whatever you send there when the flow ends in your callback endpoint.

In this [sample](https://github.com/OfficeDev/Office-Add-in-Nodejs-ServerAuth/blob/cb767ca3873e3944484c532d2a1847ef5e8488e3/routes/connect.js#L24), we used passport and we did exactly that. We sent some data in the **state** parameter, and we got it back at the end of the flow along with the tokens.

You can also take a look at this [IETF article](https://tools.ietf.org/html/draft-bradley-oauth-jwt-encoded-state-04) for more in-depth information.

**Comment by kaiomagalhaes** [comment]
@Ricalo thanks for your answer, we figured out the same answer, so on the callback url that we send we pass:

```
/me/#{dataId}
```

**Comment by Ricalo** [comment]
Yes @kaiomagalhaes, something like that. However, I'd use `?state=dataId` just because some OAuth providers might not like the fragment (#). Some of them might not like:
```
http://domain/me/#dataId
```
but accept
```
http://domain/me?state=dataId
```
Just because **state** is specified in the standard. Of course, you never know and some of them will just accept either format.

Hope this helps :+1:

**Comment by kaiomagalhaes** [comment]
Thanks @Ricalo it really helps!
